name: quiz
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for the application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies for the project.
dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons package
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules package.
  flutter_lints: ^4.0.0

flutter:
  # Enables the use of material design icons.
  uses-material-design: true

  # Specifies assets to include in the project.
  assets:
    - assets/images/quiz-logo.png
